export const ACTIONS = {
  "PRODUCT_SUCCESS": "PRODUCT_SUCCESS",
  "PRODUCT_ERROR": "PRODUCT_ERROR",
  "PRODUCT_FETCHING": "PRODUCT_FETCHING",
}

export const STATUS = {
  IDLE: "IDLE",
  RESOLVED: "RESOLVED",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  REJECTED: "REJECTED",
  PENDING: "PENDING"
}