export const ACTIONS = {
  "PRODUCT_SUCCESS": "PRODUCT_SUCCESS",
  "PRODUCT_ERROR": "PRODUCT_ERROR",
  "PRODUCT_FETCHING": "PRODUCT_FETCHING",
  "ADD_TO_CART": "ADD_TO_CART",
  "REMOVE_FROM_CART": "REMOVE_FROM_CART",
  "PRODUCT_CHECKED": "PRODUCT_CHECKED",
  "PRODUCT_UNCHECKED": "PRODUCT_UNCHECKED"
}

export const STATUS = {
  IDLE: "IDLE",
  RESOLVED: "RESOLVED",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  REJECTED: "REJECTED",
  PENDING: "PENDING"
}